return {
  ["workshop-2287303119"]={
    configuration_options={
      [""]=0,
      Show_naughtiness=false,
      Show_range=false,
      T_crop=true,
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      item_info_mod=0,
      lang="auto",
      show_buddle_item=1,
      show_food_units=-1,
      show_fuel=true,
      show_fueled=3,
      show_nutrients=1,
      show_planar_resist=true,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=false,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-569043634"]={
    configuration_options={
      Health_Penalty_Generic="Unchanged",
      Health_Penalty_Maximum="Unchanged",
      Health_Penalty_Meat_Effigy="Unchanged",
      Health_Penalty_Portal="Unchanged",
      Health_Respawn_Amount="Unchanged",
      KeepInventory="Unchanged",
      KillMe="Unchanged",
      NoPlayerSkeletons="Unchanged",
      ReturnHotkey="Unchanged",
      ReturnHotkey_Mode="Closest",
      SpawnProtection="Enabled",
      campfire="Enabled",
      coldfire="Enabled",
      coldfirepit="Enabled",
      firepit="Enabled",
      reviver="Unchanged",
      skeleton="Enabled",
      usetags="Unchanged" 
    },
    enabled=true 
  },
  ["workshop-706633455"]={ configuration_options={ speedmultiplier=2 }, enabled=true } 
}